### ISSUE TITLE
[EPIC] ClusterSet Integration

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/k3k#121]
A review should be done to make sure that the virtual kubelet implementation integrates well with the ClusterSet. Specifically, the following features should be integrated/implemented/tested:
- The cluster set should be able to provide a network policy preventing clusters from accessing a cluster in another cluster set
- The cluster set should be able to specify a PSS that applies to every pod in every virtual cluster in the set
- The cluster set should be able to specify a priority class that applies to every pod in every virtual cluster in the set
- The cluster set's resource limits and defaults should apply to all workloads in every virtual cluster in the set
- Only workloads which are currently running should apply to the limits set in the cluster set
- The cluster set should specify which node type (shared vs virtual) is allowed

**Comment by enrichman** [comment]
Not yet, some of the bullet points still needs to be implemented:

- [x] The cluster set should be able to provide a network policy preventing clusters from accessing a cluster in another cluster set
- [x] The cluster set should be able to specify a PSS that applies to every pod in every virtual cluster in the set
- [ ] The cluster set should be able to specify a priority class that applies to every pod in every virtual cluster in the set
- [ ] The cluster set's resource limits and defaults should apply to all workloads in every virtual cluster in the set
- [ ] Only workloads which are currently running should apply to the limits set in the cluster set
- [ ] The cluster set should specify which node type (shared vs virtual) is allowed

**Comment by ShylajaDevadiga** [comment]
Closing as all the sub-issues mentioned above are validated.
